version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    parameters:
      ruby-version:
        type: string
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - ruby/install:
          version: << parameters.ruby-version >>
      - run: ruby -v
      - ruby/install-deps

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ["2.6.8", "2.6.10", "2.7.6", "3.0.3", "3.1.3", "3.2.0"]
              image: [ "cimg/base:edge", "cimg/base:current", "cimg/base:current-22.04", "cimg/base:stable", "ubuntu:22.04", "ubuntu:20.04"]

