version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    parameters:
      ruby-version:
        type: string
      os-version:
        type: string
    docker:
      - image: cimg/base:<< parameters.os-version >>
    steps:
      - checkout
      - ruby/install:
          version: << parameters.ruby-version >>
      - run: ruby -v
      - ruby/install-deps

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ["2.6.8", "2.6.10", "2.7.6", "3.0.3", "3.1.3", "3.2.0"]
              os-version: [ "edge", "current", "current-22.04", "stable", "2023.02", "2023.02-20.04", "2023.01", "2023.01-20.04", "2022.12", "2022.12-20.04"]

